In [43]:
import pandas as pd

url = 'https://en.wikipedia.org/wiki/World_population'

tables = pd.read_html(url)
table_length = len(tables)

table_1 = tables[0]
table_2 = tables[1]
table_3 = tables[2]
table_4 = tables[3]
table_5 = tables[4]
table_6 = tables[5]
table_7 = tables[6]
table_8 = tables[7]
table_9 = tables[8]
table_10 = tables[9]
table_11 = tables[10]
table_12 = tables[11]
table_13 = tables[12]
table_14 = tables[13]
table_15 = tables[14]

# Assuming the table has an over head main banner text which you want to remove
#clean_table_1 = # insert table variable which you want to remove the main head text banner e.g table_x

# To drop out a row or column you do not need
# Let us use table_5 as example
# We want to drop percentage of the world as there is no data in that column
# To drop a column set axis = 1, for row, set axis = 0. Remember an array/matrix is RXC
clean_table_2 = table_5
clean_table_2 = clean_table_2.drop('Percentage of the world', axis=1)

# Assuming we want to set the column Rank as the index
clean_table_2 = clean_table_2.set_index('Rank')

# To finally store this cleaned data
clean_table_2.to_html("C:\\Users\\User\\Desktop\\Machine Learning and Data Science\\UNZIP_FOR_NOTEBOOKS_FINAL\\DATA\\Wiki_population_data.html",index=True)

In [44]:
clean_table_2

,Country / Dependency,Population,Date,Source (official or from the United Nations)
Rank,,,,
1,China,1412600000,31 Dec 2021,National annual estimate[94]
2,India,1373761000,1 Mar 2022,Annual national estimate[95]
3,United States,333329876,15 Nov 2022,National population clock[96]
4,Indonesia,272248500,1 Jul 2021,National annual estimate[97]
5,Pakistan,229488994,1 Jul 2022,UN projection[98]
6,Nigeria,216746934,1 Jul 2022,UN projection[98]
7,Brazil,215395417,15 Nov 2022,National population clock[99]
8,Bangladesh,168220000,1 Jul 2020,Annual Population Estimate[100]
9,Russia,147190000,1 Oct 2021,2021 preliminary census results[101]
10,Mexico,128271248,31 Mar 2022,National quarterly estimate[102]