In [11]:
import numpy as np
import pandas as pd

# creating a dataframe reading from a CSV file
df = pd.read_csv("C:\\Users\\User\\Desktop\\Machine Learning and Data Science\\UNZIP_FOR_NOTEBOOKS_FINAL\DATA\\tips.csv")

# When interested in a single column data
# Example. from the read file, we want to explore the total bill column
single_column = df["total_bill"]

# When interested in a multiple column data
# Example. from the read file, we want to explore the total bill, and tip columns
multiple_columns = ["total_bill", "tip"]
df[multiple_columns]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]